const works = [
  {
    id: 1,
    title: "آب و هوا",
    text: "جاوااسکریپت",
    img: "./images/portfolio/wheather-js.jpg",
    href: "https://weather-app-o782.onrender.com",
  },
  {
    id: 2,
    title: "کافی شاپ",
    text: "HTML&CSS",
    img: "./images/portfolio/coffee-shop-html&css.jpg",
    href: "https://coffee-shop-3wkm.onrender.com",
  },
  {
    id: 3,
    title: "ساعت آنالوگ",
    text: "جاوااسکریپت",
    img: "./images/portfolio/clock-js.jpg",
    href: "https://clock-6buf.onrender.com",
  },
  {
    id: 4,
    title: "بازی حدس کلمه",
    text: "جاوااسکریپت",
    img: "./images/portfolio/guess-word-js.jpg",
    href: "https://guess-word-game.onrender.com",
  },
  {
    id: 5,
    title: "تبدیل عکس به پی دی اف",
    text: "جاوااسکریپت",
    img: "./images/portfolio/img-to-pdf-js.jpg",
    href: "https://img-to-pdf.onrender.com",
  },
  {
    id: 6,
    title: "کیبورد",
    text: "جاوااسکریپت",
    img: "./images/portfolio/keyboard-js.jpg",
    href: "https://keyboard-5ssq.onrender.com",
  },
  {
    id: 7,
    title: "ماساژ",
    text: "ریکت",
    img: "./images/portfolio/massage-react.jpg",
    href: "https://massage.onrender.com",
  },
  {
    id: 8,
    title: "شبکه اجتماعی",
    text: "HTML&CSS",
    img: "./images/portfolio/social-media-html&css.jpg",
    href: "https://instagram-7f03.onrender.com",
  },
  {
    id: 9,
    title: "برنامه آزمون",
    text: "جاوااسکریپت",
    img: "./images/portfolio/quiz-app-js.jpg",
    href: "https://quiz-app-5d6r.onrender.com",
  },
  {
    id: 10,
    title: "دیجی کالا",
    text: "ریکت",
    img: "./images/portfolio/digikala-react.jpg",
    href: "https://my-digikala.netlify.app/",
  },
  {
    id: 11,
    title: "ویرگول",
    text: "ریکت",
    img: "./images/portfolio/virgool-react.jpg",
    href: "https://virgol.netlify.app/",
  },
  {
    id: 12,
    title: "اینستاگرام",
    text: "ریکت",
    img: "./images/portfolio/instagram-react.jpg",
    href: "https://my-instagram-64.netlify.app/",
  },
];

export { works };
